language: java
jdk:
  - oraclejdk8

#script: mvn clean javadoc:jar source:jar package install deploy --settings travis-settings.xml

after_success:
  - mvn clean javadoc:jar source:jar package install deploy --settings travis-settings.xml

branches:
  only:
    - master

